package:
  name: platformio-framework-arduinoteensy
  version: 1.136.0

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 2

requirements:
  build:
    - python
    - pywget
    - platformio-platform-teensy >=2.0.0
    # Include `git`, since it includes `tar`
    - git # [win]
